name: epicpinball
version: "1.2-shareware"
summary: Epic Pinball shareware installer
description: |
  Epic Pinball is a collection of pinball games. This will install the shareware version with a single table. Buy the full version at GOG.com.
confinement: strict
grade: stable
base: core18

apps:
  epicpinball:
    command: $SNAP/launcher
    plugs:  [unity7, pulseaudio, opengl, network, x11]
    extensions: [gnome-3-28]

parts:
  launch:
    plugin: dump
    source: launcher
    stage-packages:
      - wget
      - unzip
      - yad
      - perl-base
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  dosbox-staging:
    source: https://github.com/dreamer/dosbox-staging.git
    plugin: autotools
    build-packages:
      - xvfb
      - libtool
      - build-essential
      - libsdl2-dev
      - libsdl2-net-dev
      - libncurses-dev
      - libopusfile-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-net-2.0-0
      - libopusfile0
      - libglu1-mesa
      - libpng16-16
    prime:
      - -share
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man

  cleanup:
    after: [launch, dosbox-staging]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done
