#!/bin/bash

set -e
set -o pipefail

fail () {
	yad --width=300 --title="$1" --text="$2" --text-align=center --button=gtk-ok:1 --center
}

GAMEDIR=epic_pinball_shareware

if [ ! -d $SNAP_USER_DATA/$GAMEDIR/shareware ];
then
	echo "Game directory does not exist"
	echo "Creating directory"
	mkdir -p $SNAP_USER_DATA/$GAMEDIR
	echo "Copying game to directory"
	cd $SNAP_USER_DATA/$GAMEDIR
	wget https://archive.org/download/epic_pinball_11/epic_pinball.zip -t 5 --timeout 10 2>&1 | \
	perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
	yad --progress --title="Downloading Epic Pinball" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape \
	|| fail "Network Error" "Could not access network to download game files.\n\nPlease check the network status."
	unzip -d shareware epic_pinball.zip \
	|| fail "Error" "Could not extract game files.\n\nThe download may have been corrupted"
fi

cd $SNAP_USER_DATA/$GAMEDIR
cp $SNAP/dosbox_distrib.conf .

if [ -f $SNAP_USER_DATA/$GAMEDIR/dosbox.conf ];
then
	echo "Using custom configuration"
	dosbox -conf dosbox.conf
else
	echo "Using default configuration"
	dosbox -conf dosbox_distrib.conf
fi
